#2 done
rzepinskip/travel-rec pull request #4
Opened 2020-01-07 22:59 UTC by BlackSmithPL

#2 done

2020-01-08 10:04 UTC, rzepinskip requested changes

2020-01-08 10:04 UTC, rzepinskip commented on travelrec/similarity.py
> +                        except:
Specify error type for except block

2020-01-08 10:04 UTC, rzepinskip commented on travelrec/similarity.py
> +                top_words.append(None)
I always prefer returning empty list instead of list of None

2020-01-08 10:04 UTC, rzepinskip commented on tests/test_similarity.py
> +import unittest
I prefer `pytest` due to `pytest.mark.parametrize` and `pytest.fixture` decorators. You can use them to provide list of examples to test and have each example as separate test. I am not sure whether there is a equivalent feature in `unittest`.

2020-01-08 10:04 UTC, rzepinskip commented on tests/test_similarity.py
> +        for i in range(0, len(words)):
Default lower bound of range is 0, so you can use `for i in range(len(words)):`. Even more pythonic version would be `for synonym, filter, word in zip(correct_synonym, filters, words):`

2020-01-08 10:04 UTC, rzepinskip commented on tests/test_similarity.py
> +            self.assertEqual(len(similarities), len(results[i]))
To compare lists use `assertListEqual` - https://stackoverflow.com/a/31832447
In pytest there is simple overload for `assert` - https://stackoverflow.com/a/46933938

2020-01-08 10:04 UTC, rzepinskip commented on travelrec/similarity.py
> +                            print(f"can't comapre {a} and {b}")
Misspelling

2020-01-08 10:04 UTC, rzepinskip commented on travelrec/nlp_extender.py
> +class NlpExtender():
Rename to `ProcessedStatement`?

2020-01-09 11:01 UTC, BlackSmithPL commented on travelrec/similarity.py
> +                top_words.append(None)
Maby I did not understand what you intended to be the output of this method. Isn't it a list of closest synonyms of given words in same order? In pipeline.py line 43 you use only first element of returned array.
What is your idea about that?

2020-01-09 11:13 UTC, BlackSmithPL commented on tests/test_similarity.py
> +import unittest
Ok, it sounds great, but I had problems with imports from travelrec if tests are in separate directory
> ModuleNotFoundError: No module named 'travelrec'
I didn't find any easy solution, howewer I'm new to python. If you have expirience with that, could you please configure one simple test using imports from travelrec?

2020-01-09 11:18 UTC, rzepinskip commented on travelrec/similarity.py
> +                top_words.append(None)
I thought of it as keywords detected for specified input words. I used only first one for demonstration purposes, we should use all of them.

2020-01-09 11:19 UTC, rzepinskip commented on tests/test_similarity.py
> +import unittest
You have to install our package in dev mode `pip install -e .`

2020-01-09 15:24 UTC, rzepinskip approved these changes

2020-01-09 15:24 UTC, merged